#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librsvg
Version  : 2.46.3
Release  : 41
URL      : https://download.gnome.org/sources/librsvg/2.46/librsvg-2.46.3.tar.xz
Source0  : https://download.gnome.org/sources/librsvg/2.46/librsvg-2.46.3.tar.xz
Summary  : SVG rendering library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 HPND ICU LGPL-2.1 MIT MPL-2.0-no-copyleft-exception Unlicense
Requires: librsvg-bin = %{version}-%{release}
Requires: librsvg-data = %{version}-%{release}
Requires: librsvg-lib = %{version}-%{release}
Requires: librsvg-license = %{version}-%{release}
Requires: librsvg-locales = %{version}-%{release}
Requires: librsvg-man = %{version}-%{release}
BuildRequires : atk-dev
BuildRequires : atk-dev32
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : freetype-dev
BuildRequires : freetype-dev32
BuildRequires : fribidi-dev
BuildRequires : fribidi-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : gtk3-dev
BuildRequires : gtk3-dev32
BuildRequires : libpng-dev
BuildRequires : libpng-dev32
BuildRequires : libxslt-bin
BuildRequires : pango-dev
BuildRequires : pango-dev32
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config
BuildRequires : pkgconfig(32cairo)
BuildRequires : pkgconfig(32cairo-gobject)
BuildRequires : pkgconfig(32cairo-png)
BuildRequires : pkgconfig(32fontconfig)
BuildRequires : pkgconfig(32freetype2)
BuildRequires : pkgconfig(32gdk-pixbuf-2.0)
BuildRequires : pkgconfig(32gio-2.0)
BuildRequires : pkgconfig(32gio-unix-2.0)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32gmodule-2.0)
BuildRequires : pkgconfig(32gthread-2.0)
BuildRequires : pkgconfig(32libcroco-0.6)
BuildRequires : pkgconfig(32libxml-2.0)
BuildRequires : pkgconfig(32pangocairo)
BuildRequires : pkgconfig(32pangoft2)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(cairo-png)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libcroco-0.6)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pangoft2)
BuildRequires : rust-std32
BuildRequires : rustc
BuildRequires : util-linux
BuildRequires : zlib-dev
BuildRequires : zlib-dev32

%description
# Introduction: the sleep module
The code in this module governs when worker threads should go to
sleep. This is a tricky topic -- the work-stealing algorithm relies on
having active worker threads running around stealing from one
another. But, if there isn't a lot of work, this can be a bit of a
drag, because it requires high CPU usage.

%package bin
Summary: bin components for the librsvg package.
Group: Binaries
Requires: librsvg-data = %{version}-%{release}
Requires: librsvg-license = %{version}-%{release}

%description bin
bin components for the librsvg package.


%package data
Summary: data components for the librsvg package.
Group: Data

%description data
data components for the librsvg package.


%package dev
Summary: dev components for the librsvg package.
Group: Development
Requires: librsvg-lib = %{version}-%{release}
Requires: librsvg-bin = %{version}-%{release}
Requires: librsvg-data = %{version}-%{release}
Provides: librsvg-devel = %{version}-%{release}
Requires: librsvg = %{version}-%{release}
Requires: librsvg = %{version}-%{release}

%description dev
dev components for the librsvg package.


%package dev32
Summary: dev32 components for the librsvg package.
Group: Default
Requires: librsvg-lib32 = %{version}-%{release}
Requires: librsvg-bin = %{version}-%{release}
Requires: librsvg-data = %{version}-%{release}
Requires: librsvg-dev = %{version}-%{release}

%description dev32
dev32 components for the librsvg package.


%package doc
Summary: doc components for the librsvg package.
Group: Documentation
Requires: librsvg-man = %{version}-%{release}

%description doc
doc components for the librsvg package.


%package lib
Summary: lib components for the librsvg package.
Group: Libraries
Requires: librsvg-data = %{version}-%{release}
Requires: librsvg-license = %{version}-%{release}

%description lib
lib components for the librsvg package.


%package lib32
Summary: lib32 components for the librsvg package.
Group: Default
Requires: librsvg-data = %{version}-%{release}
Requires: librsvg-license = %{version}-%{release}

%description lib32
lib32 components for the librsvg package.


%package license
Summary: license components for the librsvg package.
Group: Default

%description license
license components for the librsvg package.


%package locales
Summary: locales components for the librsvg package.
Group: Default

%description locales
locales components for the librsvg package.


%package man
Summary: man components for the librsvg package.
Group: Default

%description man
man components for the librsvg package.


%prep
%setup -q -n librsvg-2.46.3
pushd ..
cp -a librsvg-2.46.3 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571852708
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -fcf-protection=full -ffat-lto-objects -flto=4 -fstack-protector-strong "
%configure --disable-static --enable-introspection --enable-vala
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static --enable-introspection --enable-vala ; sed -i 's|cross_compiling=no|cross_compiling=yes|' configure ; ./configure RUST_TARGET=i586-unknown-linux-gnu --enable-introspection  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}   CARGO_TARGET_ARGS=--target=i586-unknown-linux-gnu
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1571852708
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librsvg
cp %{_builddir}/librsvg-2.46.3/COPYING.LIB %{buildroot}/usr/share/package-licenses/librsvg/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/librsvg-2.46.3/vendor/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/alga/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/librsvg-2.46.3/vendor/approx/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/librsvg-2.46.3/vendor/arrayvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/arrayvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/39c13e52bbc0cee5549d36f3829693726fb50a8b
cp %{_builddir}/librsvg-2.46.3/vendor/atty/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/3acad00f27f89710cd66d3f5528aed5046ac28d9
cp %{_builddir}/librsvg-2.46.3/vendor/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/e6d32072ef5f584a805b429ecbd4eec428316dde
cp %{_builddir}/librsvg-2.46.3/vendor/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/bstr/COPYING %{buildroot}/usr/share/package-licenses/librsvg/93e25f7a8d77fb5a09acece508d3651054a1b123
cp %{_builddir}/librsvg-2.46.3/vendor/bstr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/bstr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a
cp %{_builddir}/librsvg-2.46.3/vendor/byteorder/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/cairo-rs/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
cp %{_builddir}/librsvg-2.46.3/vendor/cairo-rs/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/cairo-sys-rs/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/cast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/cast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/e5c5af8ddef19fbd109a06b28365d6ab491c5a38
cp %{_builddir}/librsvg-2.46.3/vendor/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3b042d3d971924ec0296687efd50dbe08b734976
cp %{_builddir}/librsvg-2.46.3/vendor/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2111f90a2fa5afba10ae753c5ca31a1d8080f597
cp %{_builddir}/librsvg-2.46.3/vendor/criterion-plot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/4bcb9009d078c2a3a7732cf87cb86488686f34f8
cp %{_builddir}/librsvg-2.46.3/vendor/criterion-plot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/88b026af7175e69876c3c75a748724353bad2230
cp %{_builddir}/librsvg-2.46.3/vendor/criterion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/criterion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/b18f451b891c20c5648f7a3034908508f49f015b
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/144111aa0f14ef5a181326683aa9ebbd9252bca6
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-queue/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-queue/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-queue/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/librsvg/3d70df511ef55bcc4a0d2118054444f59b31e31e
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/144111aa0f14ef5a181326683aa9ebbd9252bca6
cp %{_builddir}/librsvg-2.46.3/vendor/cssparser-macros/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/9744cedce099f727b327cd9913a1fdc58a7f5599
cp %{_builddir}/librsvg-2.46.3/vendor/cssparser/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/9744cedce099f727b327cd9913a1fdc58a7f5599
cp %{_builddir}/librsvg-2.46.3/vendor/csv-core/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/csv-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/csv-core/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/csv/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/csv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/csv/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/data-url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/data-url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/738188f5fed28a950b0fede659706238ec35f8bb
cp %{_builddir}/librsvg-2.46.3/vendor/downcast-rs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
cp %{_builddir}/librsvg-2.46.3/vendor/downcast-rs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4b641c95e9871464cb67aefd0a917533555e5010
cp %{_builddir}/librsvg-2.46.3/vendor/dtoa-short/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/d22157abc0fc0b4ae96380c09528e23cf77290a9
cp %{_builddir}/librsvg-2.46.3/vendor/dtoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/dtoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3a86cfdfa553511b381388859c9e94ce9e1f916b
cp %{_builddir}/librsvg-2.46.3/vendor/encoding/LICENSE.txt %{buildroot}/usr/share/package-licenses/librsvg/ea6b3b8dafcd9331dd88deb15dc9d4fb91ddd386
cp %{_builddir}/librsvg-2.46.3/vendor/float-cmp/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/9a2c2f0fce0b1eb2f7fe4125fb6f11dee3bf37ae
cp %{_builddir}/librsvg-2.46.3/vendor/fragile/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/librsvg-2.46.3/vendor/fuchsia-cprng/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/e082d0438f395b9128436ab6628c7a96c009426d
cp %{_builddir}/librsvg-2.46.3/vendor/futf/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/futf/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/6fc7897021205e271da51720736b06f9b5df3538
cp %{_builddir}/librsvg-2.46.3/vendor/gdk-pixbuf-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/gdk-pixbuf/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
cp %{_builddir}/librsvg-2.46.3/vendor/gdk-pixbuf/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/0fe9379fe01cd1deeed3046c4032f1c1be8aa594
cp %{_builddir}/librsvg-2.46.3/vendor/generic-array/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/cb74eb831db08b7fe98f84b59c9bda195e5a3588
cp %{_builddir}/librsvg-2.46.3/vendor/gio-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/gio/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
cp %{_builddir}/librsvg-2.46.3/vendor/gio/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/glib-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/glib/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
cp %{_builddir}/librsvg-2.46.3/vendor/glib/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/gobject-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/738188f5fed28a950b0fede659706238ec35f8bb
cp %{_builddir}/librsvg-2.46.3/vendor/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3a86cfdfa553511b381388859c9e94ce9e1f916b
cp %{_builddir}/librsvg-2.46.3/vendor/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/language-tags/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/f3664de17b3a5309003c1c75a9330b6b7b5866da
cp %{_builddir}/librsvg-2.46.3/vendor/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
cp %{_builddir}/librsvg-2.46.3/vendor/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/libm/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/libm/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/744183c4ca46703f4b738aca20e238e11c9a3b12
cp %{_builddir}/librsvg-2.46.3/vendor/locale_config/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/2e040ff5e44fbd2796ade7bce886a226ea10f651
cp %{_builddir}/librsvg-2.46.3/vendor/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/markup5ever/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/markup5ever/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/7f358d75b6f5bd544ce84621510900e11b27d3ba
cp %{_builddir}/librsvg-2.46.3/vendor/matches/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/1b0e913d41a66c988376898aa995d6c2f45bb50c
cp %{_builddir}/librsvg-2.46.3/vendor/matrixmultiply/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/matrixmultiply/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3bdce0683ebc036dfcc97c65499ccd030c2f1f0d
cp %{_builddir}/librsvg-2.46.3/vendor/memchr/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/02bf11a87b9bbacedf2fcf4856af3b933faef82e
cp %{_builddir}/librsvg-2.46.3/vendor/nalgebra/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/3669eaaf397f72c15424279dd618e4cc8976051a
cp %{_builddir}/librsvg-2.46.3/vendor/new_debug_unreachable/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/108bb98fdf8f27765ea240d80481be8362175ca7
cp %{_builddir}/librsvg-2.46.3/vendor/nodrop/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/nodrop/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/39c13e52bbc0cee5549d36f3829693726fb50a8b
cp %{_builddir}/librsvg-2.46.3/vendor/num-complex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/num-complex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/num-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/num-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/num-rational/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/num-rational/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
cp %{_builddir}/librsvg-2.46.3/vendor/objc/LICENSE.txt %{buildroot}/usr/share/package-licenses/librsvg/b6701831988d077f53d90abce09a2887fc7b5ea9
cp %{_builddir}/librsvg-2.46.3/vendor/pango-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/pango/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
cp %{_builddir}/librsvg-2.46.3/vendor/pango/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/pangocairo-sys/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
cp %{_builddir}/librsvg-2.46.3/vendor/pangocairo/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/429a42dedcccc15e2ae5b3de6de2773061e9be67
cp %{_builddir}/librsvg-2.46.3/vendor/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/738188f5fed28a950b0fede659706238ec35f8bb
cp %{_builddir}/librsvg-2.46.3/vendor/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3b042d3d971924ec0296687efd50dbe08b734976
cp %{_builddir}/librsvg-2.46.3/vendor/precomputed-hash/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/afcd08e00b65f2380ab5b0aa0217e8d62aa3cb2a
cp %{_builddir}/librsvg-2.46.3/vendor/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3b042d3d971924ec0296687efd50dbe08b734976
cp %{_builddir}/librsvg-2.46.3/vendor/procedural-masquerade/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/procedural-masquerade/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/c876d9954ac20b5a17c6b4995d206242620a56e9
cp %{_builddir}/librsvg-2.46.3/vendor/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
cp %{_builddir}/librsvg-2.46.3/vendor/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core-0.3.1/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core-0.3.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core-0.3.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_hc/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_hc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_hc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2e87f5a7544123079270e8178a5ab0bbd19d0e51
cp %{_builddir}/librsvg-2.46.3/vendor/rand_isaac/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_isaac/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_isaac/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_jitter/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_jitter/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_jitter/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_os/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_os/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_os/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_pcg/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_pcg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_pcg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ac1dc5ec3778e81d0e4041cc84de9f32fd81c663
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xorshift/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xorshift/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xorshift/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xoshiro/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xoshiro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/rand_xoshiro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/5917b83703c45ee336ab2f536d7a0ac46e94e1ff
cp %{_builddir}/librsvg-2.46.3/vendor/rawpointer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/rawpointer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/3a86cfdfa553511b381388859c9e94ce9e1f916b
cp %{_builddir}/librsvg-2.46.3/vendor/rayon-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/rayon-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
cp %{_builddir}/librsvg-2.46.3/vendor/rayon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/rayon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
cp %{_builddir}/librsvg-2.46.3/vendor/rctree/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/999d830bf37b3d283a81b523a975ab286fd90ee3
cp %{_builddir}/librsvg-2.46.3/vendor/rdrand/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/ced8b50e816dfeba0fa899df8f5526a8ec1c1d0b
cp %{_builddir}/librsvg-2.46.3/vendor/regex-automata/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/regex-automata/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/regex-automata/data/fowler-tests/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/553e82bef8637312393c95bc62e23e8f81fd9e47
cp %{_builddir}/librsvg-2.46.3/vendor/regex-automata/data/tests/fowler/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/553e82bef8637312393c95bc62e23e8f81fd9e47
cp %{_builddir}/librsvg-2.46.3/vendor/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/librsvg/68d12a03b339648117165b9c021b93f26974d6f6
cp %{_builddir}/librsvg-2.46.3/vendor/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/regex/src/testdata/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/553e82bef8637312393c95bc62e23e8f81fd9e47
cp %{_builddir}/librsvg-2.46.3/vendor/rustc_version/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/rustc_version/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
cp %{_builddir}/librsvg-2.46.3/vendor/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/librsvg-2.46.3/vendor/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/librsvg/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
cp %{_builddir}/librsvg-2.46.3/vendor/same-file/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2ad1215c12bd0a3492399dc438aa63084323c662
cp %{_builddir}/librsvg-2.46.3/vendor/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
cp %{_builddir}/librsvg-2.46.3/vendor/semver-parser/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/semver-parser/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/da31fe66a3349c85f4ca594c232d82ac4f02a76b
cp %{_builddir}/librsvg-2.46.3/vendor/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
cp %{_builddir}/librsvg-2.46.3/vendor/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/siphasher/COPYING %{buildroot}/usr/share/package-licenses/librsvg/1fa93df46254c46478d6aad7df9ec5e199694113
cp %{_builddir}/librsvg-2.46.3/vendor/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/c61640f6c218caf86d1b8072e09668a8362dba04
cp %{_builddir}/librsvg-2.46.3/vendor/string_cache/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/string_cache/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/6c2945f449081ab19640fb7c70a081a1a4559399
cp %{_builddir}/librsvg-2.46.3/vendor/string_cache_codegen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/string_cache_codegen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/6c2945f449081ab19640fb7c70a081a1a4559399
cp %{_builddir}/librsvg-2.46.3/vendor/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
cp %{_builddir}/librsvg-2.46.3/vendor/tendril/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/tendril/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/6fc7897021205e271da51720736b06f9b5df3538
cp %{_builddir}/librsvg-2.46.3/vendor/textwrap/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/70e36c2f54755e87728778c41ab4b809e5b0b502
cp %{_builddir}/librsvg-2.46.3/vendor/thread_local/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/thread_local/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
cp %{_builddir}/librsvg-2.46.3/vendor/tinytemplate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/tinytemplate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/5875ddc227c505ff2ad6e06538e1d72d403b9060
cp %{_builddir}/librsvg-2.46.3/vendor/typenum/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/5984f5244c7bc13bf15a5bea823c04ec0bbc714f
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/5ed53061419caf64f84d064f3641392a2a10fa7f
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/5ed53061419caf64f84d064f3641392a2a10fa7f
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-xid/COPYRIGHT %{buildroot}/usr/share/package-licenses/librsvg/5ed53061419caf64f84d064f3641392a2a10fa7f
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-xid/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/unicode-xid/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
cp %{_builddir}/librsvg-2.46.3/vendor/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
cp %{_builddir}/librsvg-2.46.3/vendor/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/738188f5fed28a950b0fede659706238ec35f8bb
cp %{_builddir}/librsvg-2.46.3/vendor/walkdir/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
cp %{_builddir}/librsvg-2.46.3/vendor/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
cp %{_builddir}/librsvg-2.46.3/vendor/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2ad1215c12bd0a3492399dc438aa63084323c662
cp %{_builddir}/librsvg-2.46.3/vendor/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
cp %{_builddir}/librsvg-2.46.3/vendor/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/librsvg/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/librsvg-2.46.3/vendor/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/librsvg/2243f7a86daaa727d34d92e987a741036f288464
cp %{_builddir}/librsvg-2.46.3/vendor/xml-rs/LICENSE %{buildroot}/usr/share/package-licenses/librsvg/8318ca66788e87585fb4cbb4b5e6b90c3dc6f34f
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang librsvg

%files
%defattr(-,root,root,-)
/usr/lib32/girepository-1.0/Rsvg-2.0.typelib

%files bin
%defattr(-,root,root,-)
/usr/bin/rsvg-convert

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Rsvg-2.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/thumbnailers/librsvg.thumbnailer
/usr/share/vala/vapi/librsvg-2.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/librsvg-2.0/librsvg/librsvg-features.h
/usr/include/librsvg-2.0/librsvg/rsvg-cairo.h
/usr/include/librsvg-2.0/librsvg/rsvg.h
/usr/lib64/librsvg-2.so
/usr/lib64/pkgconfig/librsvg-2.0.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/librsvg-2.so
/usr/lib32/pkgconfig/32librsvg-2.0.pc
/usr/lib32/pkgconfig/librsvg-2.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/librsvg/*
/usr/share/gtk-doc/html/rsvg-2.0/RsvgHandle.html
/usr/share/gtk-doc/html/rsvg-2.0/annotation-glossary.html
/usr/share/gtk-doc/html/rsvg-2.0/api-index-full.html
/usr/share/gtk-doc/html/rsvg-2.0/ch01.html
/usr/share/gtk-doc/html/rsvg-2.0/ch02.html
/usr/share/gtk-doc/html/rsvg-2.0/home.png
/usr/share/gtk-doc/html/rsvg-2.0/index.html
/usr/share/gtk-doc/html/rsvg-2.0/left-insensitive.png
/usr/share/gtk-doc/html/rsvg-2.0/left.png
/usr/share/gtk-doc/html/rsvg-2.0/licence.html
/usr/share/gtk-doc/html/rsvg-2.0/object-tree.html
/usr/share/gtk-doc/html/rsvg-2.0/recommendations-assets.html
/usr/share/gtk-doc/html/rsvg-2.0/right-insensitive.png
/usr/share/gtk-doc/html/rsvg-2.0/right.png
/usr/share/gtk-doc/html/rsvg-2.0/rsvg-2.0.devhelp2
/usr/share/gtk-doc/html/rsvg-2.0/rsvg-Using-RSVG-with-GIO.html
/usr/share/gtk-doc/html/rsvg-2.0/rsvg-Using-RSVG-with-GdkPixbuf.html
/usr/share/gtk-doc/html/rsvg-2.0/rsvg-Using-RSVG-with-cairo.html
/usr/share/gtk-doc/html/rsvg-2.0/rsvg-Version-check-and-feature-tests.html
/usr/share/gtk-doc/html/rsvg-2.0/rsvg.html
/usr/share/gtk-doc/html/rsvg-2.0/style.css
/usr/share/gtk-doc/html/rsvg-2.0/up-insensitive.png
/usr/share/gtk-doc/html/rsvg-2.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
/usr/lib64/librsvg-2.so.2
/usr/lib64/librsvg-2.so.2.46.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
/usr/lib32/librsvg-2.so.2
/usr/lib32/librsvg-2.so.2.46.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librsvg/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/librsvg/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/librsvg/0fe9379fe01cd1deeed3046c4032f1c1be8aa594
/usr/share/package-licenses/librsvg/108bb98fdf8f27765ea240d80481be8362175ca7
/usr/share/package-licenses/librsvg/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/librsvg/1b0e913d41a66c988376898aa995d6c2f45bb50c
/usr/share/package-licenses/librsvg/1fa93df46254c46478d6aad7df9ec5e199694113
/usr/share/package-licenses/librsvg/2111f90a2fa5afba10ae753c5ca31a1d8080f597
/usr/share/package-licenses/librsvg/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/librsvg/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/librsvg/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/librsvg/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/librsvg/2e040ff5e44fbd2796ade7bce886a226ea10f651
/usr/share/package-licenses/librsvg/2e87f5a7544123079270e8178a5ab0bbd19d0e51
/usr/share/package-licenses/librsvg/3669eaaf397f72c15424279dd618e4cc8976051a
/usr/share/package-licenses/librsvg/39c13e52bbc0cee5549d36f3829693726fb50a8b
/usr/share/package-licenses/librsvg/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/librsvg/3acad00f27f89710cd66d3f5528aed5046ac28d9
/usr/share/package-licenses/librsvg/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/librsvg/3bdce0683ebc036dfcc97c65499ccd030c2f1f0d
/usr/share/package-licenses/librsvg/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/librsvg/3d70df511ef55bcc4a0d2118054444f59b31e31e
/usr/share/package-licenses/librsvg/429a42dedcccc15e2ae5b3de6de2773061e9be67
/usr/share/package-licenses/librsvg/4b641c95e9871464cb67aefd0a917533555e5010
/usr/share/package-licenses/librsvg/4bcb9009d078c2a3a7732cf87cb86488686f34f8
/usr/share/package-licenses/librsvg/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/librsvg/553e82bef8637312393c95bc62e23e8f81fd9e47
/usr/share/package-licenses/librsvg/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/librsvg/5875ddc227c505ff2ad6e06538e1d72d403b9060
/usr/share/package-licenses/librsvg/5917b83703c45ee336ab2f536d7a0ac46e94e1ff
/usr/share/package-licenses/librsvg/5984f5244c7bc13bf15a5bea823c04ec0bbc714f
/usr/share/package-licenses/librsvg/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/librsvg/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/librsvg/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/librsvg/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/librsvg/6b921d29bba26338f55924223e5fc2a7c30c8355
/usr/share/package-licenses/librsvg/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/librsvg/6fc7897021205e271da51720736b06f9b5df3538
/usr/share/package-licenses/librsvg/70e36c2f54755e87728778c41ab4b809e5b0b502
/usr/share/package-licenses/librsvg/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/librsvg/744183c4ca46703f4b738aca20e238e11c9a3b12
/usr/share/package-licenses/librsvg/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/librsvg/7f358d75b6f5bd544ce84621510900e11b27d3ba
/usr/share/package-licenses/librsvg/8318ca66788e87585fb4cbb4b5e6b90c3dc6f34f
/usr/share/package-licenses/librsvg/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/librsvg/88b026af7175e69876c3c75a748724353bad2230
/usr/share/package-licenses/librsvg/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/librsvg/93e25f7a8d77fb5a09acece508d3651054a1b123
/usr/share/package-licenses/librsvg/9744cedce099f727b327cd9913a1fdc58a7f5599
/usr/share/package-licenses/librsvg/999d830bf37b3d283a81b523a975ab286fd90ee3
/usr/share/package-licenses/librsvg/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a
/usr/share/package-licenses/librsvg/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/librsvg/9a2c2f0fce0b1eb2f7fe4125fb6f11dee3bf37ae
/usr/share/package-licenses/librsvg/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/librsvg/ac1dc5ec3778e81d0e4041cc84de9f32fd81c663
/usr/share/package-licenses/librsvg/afcd08e00b65f2380ab5b0aa0217e8d62aa3cb2a
/usr/share/package-licenses/librsvg/b18f451b891c20c5648f7a3034908508f49f015b
/usr/share/package-licenses/librsvg/b6701831988d077f53d90abce09a2887fc7b5ea9
/usr/share/package-licenses/librsvg/c5af5501a367480504c8f5e55c82a3d76105a72a
/usr/share/package-licenses/librsvg/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/librsvg/c876d9954ac20b5a17c6b4995d206242620a56e9
/usr/share/package-licenses/librsvg/cb74eb831db08b7fe98f84b59c9bda195e5a3588
/usr/share/package-licenses/librsvg/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/librsvg/ced8b50e816dfeba0fa899df8f5526a8ec1c1d0b
/usr/share/package-licenses/librsvg/d22157abc0fc0b4ae96380c09528e23cf77290a9
/usr/share/package-licenses/librsvg/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/librsvg/da31fe66a3349c85f4ca594c232d82ac4f02a76b
/usr/share/package-licenses/librsvg/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/librsvg/e082d0438f395b9128436ab6628c7a96c009426d
/usr/share/package-licenses/librsvg/e5c5af8ddef19fbd109a06b28365d6ab491c5a38
/usr/share/package-licenses/librsvg/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/librsvg/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/librsvg/ea6b3b8dafcd9331dd88deb15dc9d4fb91ddd386
/usr/share/package-licenses/librsvg/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
/usr/share/package-licenses/librsvg/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/librsvg/f3664de17b3a5309003c1c75a9330b6b7b5866da
/usr/share/package-licenses/librsvg/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rsvg-convert.1

%files locales -f librsvg.lang
%defattr(-,root,root,-)

